CLISTM_SRC_DIRS = $(UTFS_MODULE_DIRS) src/
CLISTM_BUILD_DIR = build
CLISTM_MODEL_NUM = STM32F446xx
CLISTM_HAL_MODULES = gpio adc adc_ex dma rcc_ex

.PHONY: clean
clean:
	rm -r build

include ../../command_line_stm32f4.mk
